# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from four_motor_ctrl/motorinfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class motorinfo(genpy.Message):
  _md5sum = "e2e51b2487914c67f91427adb33d8627"
  _type = "four_motor_ctrl/motorinfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 T
float32 W
float32 LW
float32 Acc 
float32 Pos
float32 KP
float32 KW
int32 mode
float32 pos_joy1"""
  __slots__ = ['T','W','LW','Acc','Pos','KP','KW','mode','pos_joy1']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','int32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       T,W,LW,Acc,Pos,KP,KW,mode,pos_joy1

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motorinfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.T is None:
        self.T = 0.
      if self.W is None:
        self.W = 0.
      if self.LW is None:
        self.LW = 0.
      if self.Acc is None:
        self.Acc = 0.
      if self.Pos is None:
        self.Pos = 0.
      if self.KP is None:
        self.KP = 0.
      if self.KW is None:
        self.KW = 0.
      if self.mode is None:
        self.mode = 0
      if self.pos_joy1 is None:
        self.pos_joy1 = 0.
    else:
      self.T = 0.
      self.W = 0.
      self.LW = 0.
      self.Acc = 0.
      self.Pos = 0.
      self.KP = 0.
      self.KW = 0.
      self.mode = 0
      self.pos_joy1 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7fif().pack(_x.T, _x.W, _x.LW, _x.Acc, _x.Pos, _x.KP, _x.KW, _x.mode, _x.pos_joy1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.T, _x.W, _x.LW, _x.Acc, _x.Pos, _x.KP, _x.KW, _x.mode, _x.pos_joy1,) = _get_struct_7fif().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7fif().pack(_x.T, _x.W, _x.LW, _x.Acc, _x.Pos, _x.KP, _x.KW, _x.mode, _x.pos_joy1))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.T, _x.W, _x.LW, _x.Acc, _x.Pos, _x.KP, _x.KW, _x.mode, _x.pos_joy1,) = _get_struct_7fif().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7fif = None
def _get_struct_7fif():
    global _struct_7fif
    if _struct_7fif is None:
        _struct_7fif = struct.Struct("<7fif")
    return _struct_7fif
